
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"
    depends_on:
      - web_server
    networks:
      - app_network

  web_server:
    build:
      context: ./web_server
    ports:
      - "5000:5000"
    networks:
      - app_network
    env_file:
      - .env
    environment:
      - FLASK_APP=backend.blueprints.__init__
      - FLASK_DEBUG=True
      
networks:
  app_network:
    driver: bridge