version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"
    depends_on:
      - flask
    networks:
      - app_network

  flask:
    build:
      context: ./web_server
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
